### ISSUE TITLE
Version requirements

### ISSUE THREAD

**Issue by patricktokeeffe** [ether/ep_disable_reset_authorship_colours#2]
The package specifies node version < 0.7 and etherpad-lite currently reqs 0.10 or better. Is that upper bound an artifact or genuine?

**Comment by patricktokeeffe** [comment]
I'm going to hazard a guess: _genuine, but plugin is superceded by https://www.npmjs.com/package/ep_remove_collab_fields_.

Feel free to close if I'm right, or I'll wander back here in a few weeks and do it. :)

**Comment by JohnMcLear** [comment]
I pushed a fix.
